apiVersion: v1
kind: Pod
metadata:
  name: nodejs-pod
spec:
  containers:
  - name: nodejs-container
    image: miadan/kubia
  resources:
     limits:
       cpu: 1000m
     requests:
       cpu: 1000m